# Generated by Django 5.1.3 on 2025-01-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_date',
        ),
    ]
