# Generated by Django 5.1.3 on 2025-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_end_date_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
