# Generated by Django 5.1.3 on 2025-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_reservation_date_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(choices=[('20-7', 'Sunset (8 PM - 7 AM)'), ('9-18', 'Sunrise (9 AM - 6 PM)'), ('20-18', 'Moon (8 PM - 6 PM)'), ('9-7', 'Star (9 AM - 7 AM)')], max_length=50),
        ),
    ]
