# Generated by Django 5.1.3 on 2025-01-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(choices=[('sunrise', 'Sunrise (9am-6pm)'), ('sunset', 'Sunset (8pm-7am)'), ('moon', 'Fullstay Moon (8pm-6pm)'), ('star', 'Fullstay Star (9am-7am)')], max_length=50),
        ),
    ]
