# Generated by Django 5.1.3 on 2024-12-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Saro', 'Cabin Saro'), ('Duwa', 'Cabin Duwa'), ('Gabos', 'Entire Resort (Gabos)')], max_length=50)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('prices_weekday', models.JSONField()),
                ('prices_weekend', models.JSONField()),
            ],
        ),
    ]
