# Generated by Django 5.1.3 on 2024-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cabins/'),
        ),
    ]
