# Generated by Django 5.1.3 on 2025-01-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0004_remove_galleryimage_gallery_cabin_max_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cabins')),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cabin',
            name='amenity',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cabin',
            name='Gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cabin', to='cabin.galleryimage'),
        ),
    ]
