# Generated by Django 5.1.3 on 2025-01-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0005_galleryimage_cabin_amenity_cabin_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(choices=[('Saro Image', 'Cabin Saro Image'), ('Duwa Image', 'Cabin Duwa Image'), ('Gabos Image', 'Cabin Gabos Image')], max_length=50, null=True),
        ),
    ]
