# Generated by Django 5.1.3 on 2025-01-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0009_remove_gallerycollection_images_remove_cabin_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cabins/')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='cabin',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabin.galleryimage'),
        ),
    ]
