# Generated by Django 5.1.3 on 2025-01-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0010_galleryimage_cabin_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabin.galleryimage'),
        ),
    ]
