# Generated by Django 5.1.3 on 2025-01-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0012_alter_cabin_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabin',
            name='gallery',
        ),
        migrations.CreateModel(
            name='CabinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cabins/gallery/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabin.cabin')),
            ],
        ),
        migrations.DeleteModel(
            name='galleryimage',
        ),
    ]
